# Generated by Django 4.2.3 on 2023-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_alter_user_id_comment_bid_auction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
