# Generated by Django 4.2.3 on 2023-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
